project:
  type: book

book:
  title: "Notes on Deep Learning"
  author: "Alexander (Sasha) Pastukhov"
  date: "11/20/2022"
  chapters:
    - index.qmd
    - 01-sdg-mean.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
